spring.application.name=tax-support-system
# サーバーの設定（ポート番号を8080に指定）
server.port=8080

# PostgreSQLへの接続設定
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
# ↓【重要】ここをご自身がPostgreSQLインストール時に決めたパスワードに書き換えてください
spring.datasource.password=password

# JPA/Hibernateの設定（SQLのログをコンソールに出力する）
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# データベースの自動更新設定（今回はすでにテーブルを作ってあるので "validate" にします）
spring.jpa.href.ddl-auto=validate